- hosts: all
  become: yes
  vars:
    venv_path: "{{ ansible_env.HOME }}/venv"
    pip_packages:
      - flwr[simulation]
      - tensorflow>=2.5,<3.0
      - numpy
      - scikit-learn
      - matplotlib
  tasks:
    - name: Ensure python-venv is installed
      package:
        name: python-venv
        state: present

    - name: Create virtual environment
      command: python -m venv {{ venv_path }}
      args:
        creates: "{{ venv_path }}/Scripts/activate"

    - name: Install pip packages in virtualenv
      ansible.builtin.pip:
        name: "{{ pip_packages }}"
        virtualenv: "{{ venv_path }}"
        virtualenv_python: python
        state: present
